version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "benchmark"
      POSTGRES_USER: "benchmark"
      POSTGRES_PASSWORD: "benchmark"
    ports:
      - "6543:5432"
    restart: unless-stopped
